export const SUCCESS_GET_POPULAR = "series/SUCCESS_GET_POPULAR";
export const POPULAR_IS_LOADING = "series/POPULAR_IS_LOADING";

export const SUCCESS_GET_LATEST = "series/SUCCESS_GET_LATEST";
export const LATEST_IS_LOADING = "series/LATEST_IS_LOADING";