export const SUCCESS_GET_GENRES = "movies/SUCCESS_GET_GENRES"
export const GENRES_IS_LOADING = "movies/GENRES_IS_LOADING"

export const SUCCESS_GET_POPULAR = "movies/SUCCESS_GET_POPULAR"
export const POPULAR_IS_LOADING = "movies/POPULAR_IS_LOADING"

export const SUCCESS_GET_PLAYING = "movies/SUCCESS_GET_PLAYING"
export const PLAYING_IS_LOADING = "movies/PLAYING_IS_LOADING"

export const SUCCESS_GET_TOP_RATED = "movies/SUCCESS_GET_TOP_RATED"
export const TOP_RATED_IS_LOADING = "movies/TOP_RATED_IS_LOADING"

export const SUCCESS_GET_UPCOMING = "movies/SUCCESS_GET_UPCOMING"
export const UPCOMING_IS_LOADING = "movies/UPCOMING_IS_LOADING"

export const SUCCESS_GET_LATEST = "movies/SUCCESS_GET_LATEST"
export const LATEST_IS_LOADING = "movies/LATEST_IS_LOADING"

export const SUCCESS_SELECT_MOVIE = "movies/SUCCESS_SELECT_MOVIE"
export const SUCCESS_ID_SELECTED_MOVIE = "movies/SUCCESS_ID_SELECTED_MOVIE"
export const TRAILER_IS_LOADING = "movies/TRAILER_IS_LOADING"

export const SUCCESS_GET_SIMILAR = "movies/SUCCESS_GET_SIMILAR"
export const SIMILAR_IS_LOADING = "movies/SIMILAR_IS_LOADING"

export const MORE_POPULAR_IS_LOADING = "movies/MORE_POPULAR_IS_LOADING"
