export const SUCCESS_GET_GENRES = "SUCCESS_GET_GENRES"
export const GENRES_IS_LOADING = "genres/IS_LOADING"

export const SUCCESS_GET_POPULAR = "SUCCESS_GET_POPULAR"
export const SUCCESS_GET_MOST_POPULAR = "SUCCESS_GET_MOST_POPULAR"
export const POPULAR_IS_LOADING = "popular/IS_LOADING"