export const SUCCESS_GET_GENRES = "SUCCESS_GET_GENRES"
export const GENRES_IS_LOADING = "genres/IS_LOADING"

export const SUCCESS_GET_POPULAR = "SUCCESS_GET_POPULAR"
export const POPULAR_IS_LOADING = "popular/IS_LOADING"

export const SUCCESS_GET_PLAYING = "SUCCESS_GET_PLAYING"
export const PLAYING_IS_LOADING = "playing/IS_LOADING"

export const SUCCESS_GET_TOP_RATED = "SUCCESS_GET_TOP_RATED"
export const TOP_RATED_IS_LOADING = "topRated/IS_LOADING"

export const SUCCESS_GET_UPCOMING = "SUCCESS_GET_UPCOMING"
export const UPCOMING_IS_LOADING = "upcoming/IS_LOADING"

export const SUCCESS_GET_LATEST = "SUCCESS_GET_LATEST"
export const LATEST_IS_LOADING = "latest/IS_LOADING"

export const SUCCESS_SELECT_MOVIE = "SUCCESS_SELECT_MOVIE"
export const SUCCESS_ID_SELECTED_MOVIE = "SUCCESS_ID_SELECTED_MOVIE"
export const TRAILER_IS_LOADING = "trailerLoading/IS_LOADING"